#oh my zsh
export ZSH="$HOME/.oh-my-zsh"

# oh my zsh settings
plugins=(git)
ZSH_THEME="sonicradish"
ENABLE_CORRECTION="true"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Start tmux at shell spawn
if [ "$TMUX" = "" ]; then tmux; fi

# User specific aliases and functions
if [ -d ~/.rc.d ]; then
  for rc in ~/.rc.d/*.rc; do
    if [ -f "$rc" ]; then
      . "$rc"
    fi
  done
else
  mkdir -p ~/.rc.d
fi

unset rc

# Enable zoxide
eval "$(zoxide init zsh)"
alias cd="z"

# if using oh my zsh make sure to source everything BEFORE the oh-my-zsh.sh source
source $ZSH/oh-my-zsh.sh
