#oh my zsh
export ZSH="$HOME/.oh-my-zsh"

# oh my zsh settings
plugins=(git fzf-zsh-plugin zsh-autosuggestions)
ZSH_THEME="sonicradish"
ENABLE_CORRECTION="true"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

# Start tmux at shell spawn
if [ "$TMUX" = "" ]; then tmux; fi

# User specific aliases and functions
if [ -d ~/.rc.d ]; then
  if [ "$(ls -A ~/.rc.d)" ]; then
    for rc in ~/.rc.d/*.rc; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
  fi
else
  mkdir -p ~/.rc.d
  touch ~/.rc.d/aliases.rc
  # Set up aliases.rc
  echo "alias lla='ls -lha --color=auto'" >> ~/.rc.d/aliases.rc
  echo "alias sshconfig='$EDITOR ~/.ssh/config'" >> ~/.rc.d/aliases.rc
  echo "alias zshconfig='$EDITOR ~/.zshrc'" >> ~/.rc.d/aliases.rc
  echo "alias aliases='$EDITOR ~/.rc.d/aliases.rc'" >> ~/.rc.d/aliases.rc
  echo "alias custompaths='$EDITOR ~/.rc.d/custompaths.rc'" >> ~/.rc.d/aliases.rc
  touch ~/.rc.d/custompaths.rc
  # Set up custompaths.rc
  echo -n "#Add local user directory\nexport PATH=\$PATH:~/.local/bin" >> ~/.rc.d/custompaths.rc
fi

unset rc

# Check if zoxide is installed
if command -v zoxide &>/dev/null; then
  # Enable zoxide
  eval "$(zoxide init zsh)"
  alias cd="z"
fi

# Keyring fix
export SSH_AGENT_PID=`pidof ssh-agent`
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
export GNOME_KEYRING_CONTROL=/run/user/1000/keyring

# if using oh my zsh make sure to source everything BEFORE the oh-my-zsh.sh source
source $ZSH/oh-my-zsh.sh
